name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore /BowlingCounterApp
    - name: Build
      run: dotnet build BowlingCounterApp.Tests/BowlingCounterApp.Tests.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test BowlingCounterApp.Tests/BowlingCounterApp.Tests.csproj --no-restore --verbosity normal
